C
C Error file for the catalogue system
C
C Illegal catalogue entry
       integer    ill_catent
       parameter (ill_catent  =-2230) 
C Catalogue entry already allocated
       integer    ill_catuse
       parameter (ill_catuse  =-7035)
C Catalogue entry not available for write
       integer    ill_catwrt
       parameter (ill_catwrt  =-7040) 
C Catalogue entry not available for read
       integer    ill_catrd
       parameter (ill_catrd   =-7045) 
C Catalogue file not open
       integer    ill_catope
       parameter (ill_catope  =-2250) 



