C
C Global parameter file
C

C catalogue system defaults
       character*6  default_cat_dir
       parameter   (default_cat_dir = '~/mrao' )
       character*5  default_cat_file
       parameter   (default_cat_file = 'image' )
       character*5  default_cat_type
       parameter   (default_cat_type = 'cat' )

       character*38 ic_error_file
       parameter   (ic_error_file = 
     *             '/mrao/anmap_v7.5/include/ic_errors.inc')

